#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations
python manage.py migrate
python manage.py addAdmin
python manage.py addChannels
# exec python manage.py runworker
exec python manage.py runserver 0.0.0.0:8000
# exec python manage.py runserver_plus 0.0.0.0:8000
# exec docker run -p 6379:6379 -d redis:5
