version: "3"

networks:
  my_socket_ipc_network:
    driver: bridge

volumes:
  myproj_local_postgres_data: {}
  myproj_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: myproj_local_django
    container_name: myproj_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    tty: true
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    networks:
      - my_socket_ipc_network
    command: /start

  postgres:
    container_name: postgres
    image: postgres:11.1
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - myproj_local_postgres_data:/var/lib/postgresql/data
      - myproj_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    expose:
      - "5432"
    ports:
      - 5432:5432
    networks:
      - my_socket_ipc_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - 5454:5454/tcp
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=5454
    networks:
      - my_socket_ipc_network

  frontend:
    container_name: frontend
    # build: ./frontend
    image: node:lts
    working_dir: /app/
    entrypoint: /bin/bash
    ports:
      - 81:80
    volumes:
      - ./frontend/:/app:z
      # - ./frontend/nginx:/etc/nginx/conf.d
    tty: true
    networks:
      - my_socket_ipc_network

  trade_socket:
    container_name: trade_socket_server
    image: trade_socket:latest
    restart: always
    build:
      context: .
      dockerfile: ./trade_socket/Dockerfile
    ports:
      - "8080-8099:8080-8099"
    depends_on:
      - postgres
    env_file:
      - ./.envs/.local/.postgres
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - USE_DOCKER=yes
      - REDIS_URL=redis://redis:6379/0
    command: /start
    networks:
      - my_socket_ipc_network
    volumes:
      - .:/app:z
    tty: true

  reddis:
    container_name: reddis_layer
    image: redis:5
    ports:
      - 6379:6379
    tty: true
    networks:
      - my_socket_ipc_network
