# Generated by Django 4.0.8 on 2023-03-20 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schannels', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_ticket', models.CharField(max_length=255)),
                ('trade_type', models.CharField(max_length=255)),
                ('trade_price', models.CharField(max_length=255)),
                ('take_profit', models.CharField(max_length=255)),
                ('trade_date', models.CharField(max_length=255)),
                ('trade_status', models.CharField(max_length=255)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_signal', to='schannels.schannel')),
            ],
        ),
    ]
