# Generated by Django 4.0.8 on 2023-04-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signals',
            name='magic_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
