# Generated by Django 4.0.8 on 2023-01-21 05:23

from django.db import migrations, models

# from schannels.pairList import pair_list

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    # def load_initial_data(apps, schema_editor):
    #     # get_model(appname, modelname)
    #     schannels = apps.get_model('schannels', 'SChannel')
    #     for pair in pair_list():
    #         schannels.objects.create_channel (
    #             channel_name = pair
    #             )

    operations = [
        migrations.CreateModel(
            name='SChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        # migrations.RunPython(load_initial_data),
    ]
