# Generated by Django 4.0.8 on 2023-03-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
        ('schannels', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schannel',
            name='signals',
            field=models.ManyToManyField(blank=True, to='signals.signals'),
        ),
    ]
