#!/bin/bash

# set -o errexit
# set -o pipefail
# set -o nounset


# python /app/manage.py collectstatic --noinput

# exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app

set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations
python manage.py migrate
python manage.py addAdmin
python manage.py addChannels
python config/__.py
# exec python manage.py runs
